NuevoDiagramaDeClases
Theratoffqa/Algoritmica_II pull request #5
Opened 2022-11-10 15:14 UTC by Theratoffqa

![UML Hotel (actualizado)](https://user-images.githubusercontent.com/58194453/201133036-aba52078-1daa-4a6a-beff-c03387adcff4.png)

2022-11-10 16:06 UTC, JoxAQC requested changes
Flata definir algunos ambitos de encapsulamiento en el diagrama de clases, modularizar el codigo con los metodos de clase y reorganizar el main

2022-11-10 21:08 UTC, jatzirywong9 requested changes
El método actualizarCatalogo() puede ser eliminado para solo contar con los métodos de registro y actualización de las características de las habitaciones.

2022-11-11 01:16 UTC, FiorellaMirano13 approved these changes

2022-11-11 01:25 UTC, GHOPsT approved these changes
Los cambios los considero pertinentes

2022-11-11 03:04 UTC, closed without merging